;==========================================================================
; UltOS
; Scott Hutter
;
;   This file is part of UltOS.
;
;    UltOS is free software: you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation, either version 3 of the License, or
;    (at your option) any later version.
;
;    UltOS is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License
;    along with UltOS.  If not, see <https://www.gnu.org/licenses/>.
;==========================================================================

r0              =       $02
r0L             =       $02
r0H             =       $03
r1              =       $04
r1L             =       $04
r1H             =       $05
r2              =       $06
r2L             =       $06
r2H             =       $07
r3              =       $08
r3L             =       $08
r3H             =       $09
r4              =       $0a
r4L             =       $0a
r4H             =       $0b
r5              =       $0c
r5L             =       $0c
r5H             =       $0d
r6              =       $0e
r6L             =       $0e
r6H             =       $0f
r7              =       $10
r7L             =       $10
r7H             =       $11
r8              =       $12
r8L             =       $12
r8H             =       $13
r9              =       $14
r9L             =       $14
r9H             =       $15
r10             =       $16
r10L            =       $16
r10H            =       $17
r11             =       $18
r11L            =       $18
r11H            =       $19
r12             =       $1a
r12L            =       $1a
r12H            =       $1b
r13             =       $1c
r13L            =       $1c
r13H            =       $1d
r14             =       $1e
r14L            =       $1e
r14H            =       $1f
r15             =       $20
r15L            =       $20
r15H            =       $21
r16             =       $22
;
X1              =       $02
Y1              =       $04
X2              =       $06
Y2              =       $08
;
a0              =       $fb
a0L             =       $fb
a0H             =       $fc
a1              =       $fd
a1L             =       $fd
a1H             =       $fe
a2              =       $70
a2L             =       $70
a2H             =       $71
a3              =       $72
a3L             =       $72
a3H             =       $73
a4              =       $74
a4L             =       $74
a4H             =       $75
a5              =       $76
a5L             =       $76
a5H             =       $77
a6              =       $78
a6L             =       $78
a6H             =       $79
a7              =       $7a
a7L             =       $7a
a7H             =       $7b
a8              =       $7c
a8L             =       $7c
a8H             =       $7d
a9              =       $7e
a9L             =       $7e
a9H             =       $7f