;==========================================================================
; UOS
; Scott Hutter
;==========================================================================

X1          = $02
Y1          = $04
X2          = $06
Y2          = $08

r1          = $09
r2          = $0a
r3          = $0b
r4          = $0c
r5          = $0d

APP_START   = $1000
APP_CLICK   = $1500

InitGr      = $c01b
GPLOT       = $c036
GRON        = $c0c9
GROFF       = $c172
SETCOLOR    = $c18d
LINE        = $c1ac
CIRCLE      = $c379
GPUTC       = $c583
GPUTS       = $c6fa

install1    = $9f09
